// Only public payment links generated by the Robokassa merchant dashboard.
// Never put merchant passwords, API secrets or signing logic in this file.
// Enable a format only after testing its amount, receipt and fulfillment.
window.POCUS_PAYMENTS = Object.freeze({
  onsite: '', // Fixed amount: 1000 RUB. Onsite conference participation.
  online: '' // Fixed amount: 500 RUB. Configure access delivery before enabling.
});
